export const CartAction = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  UPDATE_CART: 'UPDATE_CART',
  UPDATE_DISCOUNT: 'UPDATE_DISCOUNT',
  UPDATE_BUYER_IDENTITY: 'UPDATE_BUYER_IDENTITY',
};
